package com.grpduh.budget.controller;

import java.util.List;

import com.grpduh.budget.entity.Person;
import com.grpduh.budget.repo.DataRepo;
import com.grpduh.budget.repo.PersonRepo;
import com.grpduh.budget.entity.Data;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/Budget") // This means URL's start with /demo (after Application path)
public class Endpoint {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private PersonRepo userRepository;

  @Autowired
  private DataRepo dataRepository;

  @GetMapping(path="/test")
  public @ResponseBody String index() {
      return "Hello from the Budget Controller\n";
  }

  @GetMapping(path="/{id}")
  public @ResponseBody Person getid(@PathVariable("id") int id) {
    // This returns a JSON or XML with the users
    return (Person) userRepository.findById(id);
  }

  @GetMapping(path = "/add")
    public @ResponseBody String addNewUser() {
      Person user = new Person("A","Nother");
        userRepository.save(user);
        return "User Created";
    }

  @GetMapping(path = "/allPersons")
  public @ResponseBody Iterable < Person > getAllUsers() {
      return userRepository.findAll();
  }

  @GetMapping(path = "/allData")
  public @ResponseBody Iterable < Data > getAllData() {
      return dataRepository.findAll();
  }

}